import chromium from "chrome-aws-lambda";
import puppeteer from "puppeteer";

const testHtml = `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 2.0//EN">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<html>
<head>
  <title>68k.news: Headlines From the Future</title>
</head>
<body>
  <center><h1><b>68k.news:</b> <font color="#9400d3"><i>Headlines from the Future</i></font></h1></center>
  <hr>
  <center><small>Basic HTML Google News for vintage computers. Built by <a href="https://youtube.com/ActionRetro" target="_blank"><b>Action Retro</b></a> on YouTube. Tested on Netscape 1.1 through 4 on a Mac SE/30.</small></center>
    <small>
  <p>
  <center><a href="index.php?loc=US">TOP</a> <a href="index.php?section=world&loc=US">WORLD</a> <a href="index.php?section=nation&loc=US">NATION</a> <a href="index.php?section=business&loc=US">BUSINESS</a> <a href="index.php?section=technology&loc=US">TECHNOLOGY</a> <a href="index.php?section=entertainment&loc=US">ENTERTAINMENT</a> <a href="index.php?section=sports&loc=US">SPORTS</a> <a href="index.php?section=science&loc=US">SCIENCE</a> <a href="index.php?section=health&loc=US">HEALTH</a><br>
  <font size="1">-=-=-=-=-=-=-=-=-=-=-=-=-=-</font>
  <br>US Edition <a href="choose_edition.php">(Change)</a></center>
  </p>
  </small>
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiR2h0dHBzOi8vd3d3LmNubi5jb20vMjAyMi8wMS8wMy90ZWNoL2VsaXphYmV0aC1ob2xtZXMtdmVyZGljdC9pbmRleC5odG1s0gEA?oc=5">Elizabeth Holmes found guilty on four out of 11 federal charges - CNN</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiR2h0dHBzOi8vd3d3LmNubi5jb20vMjAyMi8wMS8wMy90ZWNoL2VsaXphYmV0aC1ob2xtZXMtdmVyZGljdC9pbmRleC5odG1s0gEA?oc=5" >Elizabeth Holmes found guilty on four out of 11 federal charges</a>  CNN</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiQGh0dHBzOi8vd3d3LmZveGJ1c2luZXNzLmNvbS90ZWNobm9sb2d5L2VsaXphYmV0aC1ob2xtZXMtZGVjaXNpb27SAURodHRwczovL3d3dy5mb3hidXNpbmVzcy5jb20vdGVjaG5vbG9neS9lbGl6YWJldGgtaG9sbWVzLWRlY2lzaW9uLmFtcA?oc=5" >Elizabeth Holmes found guilty on 4 of 11 charges, jury could not reach verdict on 3</a>  Fox Business</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9U3NiQXVMcFhxenPSAQA?oc=5" >Mixed verdict in trial of Elizabeth Holmes</a>  CNBC Television</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMibmh0dHBzOi8vd3d3Lm5iY25ld3MuY29tL3RoaW5rL29waW5pb24vZWxpemFiZXRoLWhvbG1lcy10cmlhbC1maW5kcy10aGVyYW5vcy1leC1jZW8tZ3VpbHR5LTQtY291bnRzLW5jbmExMjg2ODk50gEtaHR0cHM6Ly93d3cubmJjbmV3cy5jb20vdGhpbmsvYW1wL25jbmExMjg2ODk5?oc=5" >The Elizabeth Holmes trial finds Theranos ex-CEO guilty on 4 counts of fraud. What it missed.</a>  NBCNews.com</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9WDRsdFNkNXc3RnfSAQA?oc=5" >Elizabeth Holmes Jury to Resume Deliberations After Holiday Break</a>  NBC Bay Area</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 8:16 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMijgFodHRwczovL3d3dy5pbnZlc3RvcnMuY29tL21hcmtldC10cmVuZC9zdG9jay1tYXJrZXQtdG9kYXkvZG93LWpvbmVzLWZ1dHVyZXMtdHJlYXN1cnkteWllbGRzLXN1cmdlLWFwcGxlLW1ha2VzLWhpc3RvcnktdGltZS10by1idXktdGVzbGEtc3RvY2sv0gEA?oc=5">Dow Jones Futures: Treasury Yields Surge; Apple Makes History; Time To Buy Tesla Stock? - Investor's Business Daily</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMijgFodHRwczovL3d3dy5pbnZlc3RvcnMuY29tL21hcmtldC10cmVuZC9zdG9jay1tYXJrZXQtdG9kYXkvZG93LWpvbmVzLWZ1dHVyZXMtdHJlYXN1cnkteWllbGRzLXN1cmdlLWFwcGxlLW1ha2VzLWhpc3RvcnktdGltZS10by1idXktdGVzbGEtc3RvY2sv0gEA?oc=5" >Dow Jones Futures: Treasury Yields Surge; Apple Makes History; Time To Buy Tesla Stock?</a>  Investor's Business Daily</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiTGh0dHBzOi8vd3d3LmNuYmMuY29tLzIwMjIvMDEvMDIvZnV0dXJlcy1zdG9jay1tYXJrZXQtbmV3cy1vcGVuLXRvLWNsb3NlLmh0bWzSAQA?oc=5" >Dow jumps more than 200 points to record close to start 2022, Tesla boosts Nasdaq by 1%</a>  CNBC</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiZGh0dHBzOi8vd3d3LnJldXRlcnMuY29tL21hcmtldHMvZXVyb3BlL3NwLWZ1dHVyZXMtbmVhci1yZWNvcmQtaGlnaC1icmlnaHQtc3RhcnQtbmV3LXllYXItMjAyMi0wMS0wMy_SAQA?oc=5" >Wall Street climbs in upbeat start to 2022</a>  Reuters</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMicWh0dHBzOi8vd3d3LmNoaWNhZ290cmlidW5lLmNvbS9idXNpbmVzcy9jdC1iaXotd2FsbC1zdHJlZXQtbWFya2V0cy0yMDIyMDEwMy01cmh5enRyNWhiZmRwYmRlYTZ5bXJmN256YS1zdG9yeS5odG1s0gGAAWh0dHBzOi8vd3d3LmNoaWNhZ290cmlidW5lLmNvbS9idXNpbmVzcy9jdC1iaXotd2FsbC1zdHJlZXQtbWFya2V0cy0yMDIyMDEwMy01cmh5enRyNWhiZmRwYmRlYTZ5bXJmN256YS1zdG9yeS5odG1sP291dHB1dFR5cGU9YW1w?oc=5" >After a big 2021, Wall Street starts new year with more record highs</a>  Chicago Tribune</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMicmh0dHBzOi8vd3d3LmNuYmMuY29tLzIwMjIvMDEvMDMvc3RvY2tzLW1ha2luZy10aGUtYmlnZ2VzdC1tb3Zlcy1pbi10aGUtcHJlbWFya2V0LXRlc2xhLW1jZG9uYWxkcy1uaW8tYW5kLW1vcmUuaHRtbNIBAA?oc=5" >Stocks making the biggest moves in the premarket: Tesla, McDonald's, Nio and more</a>  CNBC</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 7:56 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiW2h0dHBzOi8vd3d3LmNubi5jb20vMjAyMi8wMS8wMy9hbWVyaWNhcy9qYWlyLWJvbHNvbmFyby1ob3NwaXRhbGl6ZWQtamFudWFyeS1pbnRsL2luZGV4Lmh0bWzSAQA?oc=5">Brazil President Jair Bolsonaro hospitalized with intestinal obstruction - CNN</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiW2h0dHBzOi8vd3d3LmNubi5jb20vMjAyMi8wMS8wMy9hbWVyaWNhcy9qYWlyLWJvbHNvbmFyby1ob3NwaXRhbGl6ZWQtamFudWFyeS1pbnRsL2luZGV4Lmh0bWzSAQA?oc=5" >Brazil President Jair Bolsonaro hospitalized with intestinal obstruction</a>  CNN</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiVGh0dHBzOi8vd3d3Lm55dGltZXMuY29tLzIwMjIvMDEvMDMvd29ybGQvYW1lcmljYXMvYnJhemlsLWJvbHNvbmFyby1ob3NwaXRhbGl6ZWQuaHRtbNIBAA?oc=5" >Brazil's President, Jair Bolsonaro, Is Hospitalized</a>  The New York Times</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiZWh0dHBzOi8vYXBuZXdzLmNvbS9hcnRpY2xlL2NhcmliYmVhbi1icmF6aWwtc2FvLXBhdWxvLWphaXItYm9sc29uYXJvLWFiY2M2OGViNjM4ZjJmZjYxMTdmOTY0YThiZmViZmYw0gEA?oc=5" >Brazil's Bolsonaro hospitalized with intestinal obstruction</a>  Associated Press</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiNWh0dHBzOi8vd3d3LmJiYy5jb20vbmV3cy93b3JsZC1sYXRpbi1hbWVyaWNhLTU5ODMzMjY30gE5aHR0cHM6Ly93d3cuYmJjLmNvbS9uZXdzL3dvcmxkLWxhdGluLWFtZXJpY2EtNTk4MzMyNjcuYW1w?oc=5" >Brazil's Bolsonaro in hospital with intestinal blockage</a>  BBC News</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMidGh0dHBzOi8vd3d3LnJldXRlcnMuY29tL3dvcmxkL2FtZXJpY2FzL2JyYXppbHMtYm9sc29uYXJvLWlzLWltcHJvdmluZy1uZWVkLXN1cmdlcnktdW5jbGVhci1ob3NwaXRhbC1zYXlzLTIwMjItMDEtMDMv0gEA?oc=5" >Brazil's Bolsonaro is improving, need for surgery unclear, hospital says</a>  Reuters Canada</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 7:46 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiRWh0dHBzOi8vd3d3Lm55dGltZXMuY29tLzIwMjIvMDEvMDMvdXMvc2Nob29scy1jbGFzc3Jvb21zLW9taWNyb24uaHRtbNIBAA?oc=5">'It's Chaos' as Schools Confront Omicron - The New York Times</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiRWh0dHBzOi8vd3d3Lm55dGltZXMuY29tLzIwMjIvMDEvMDMvdXMvc2Nob29scy1jbGFzc3Jvb21zLW9taWNyb24uaHRtbNIBAA?oc=5" >'It's Chaos' as Schools Confront Omicron</a>  The New York Times</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiZ2h0dHBzOi8vd3d3Lm5wci5vcmcvMjAyMi8wMS8wMy8xMDY5OTA3NDM3L29mZmljaWFscy1hcmUtZGV0ZXJtaW5lZC10by1rZWVwLXNjaG9vbHMtb3Blbi1kZXNwaXRlLW9taWNyb27SAQA?oc=5" >Despite omicron, most schools are staying open after the holidays</a>  NPR</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiaGh0dHBzOi8vd3d3LmJhbHRpbW9yZXN1bi5jb20vZWR1Y2F0aW9uL2JzLW1kLXNjaG9vbHMtb3Blbi0yMDIyMDEwMy03dmFiN21wcWpyY3hkYzNoN2E3NmxsdWJjZS1zdG9yeS5odG1s0gEA?oc=5" >Maryland education leaders vow to keep schools open despite rapidly rising number of COVID-19 cases</a>  Baltimore Sun</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiY2h0dHBzOi8vd3d3LmlucXVpcmVyLmNvbS9uZXdzL3Nub3ctY292aWQtc2Nob29sLWNsb3N1cmVzLXBoaWxhZGVscGhpYS1wZW5uc3lsdmFuaWEtbmotMjAyMjAxMDMuaHRtbNIBAA?oc=5" >Snow and COVID-19 snarl school openings in the region; 77 Philadelphia schools will go virtual Tuesday</a>  The Philadelphia Inquirer</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiWmh0dHBzOi8vd3d3Lm55dGltZXMuY29tLzIwMjIvMDEvMDMvYnJpZWZpbmcvY29yb25hdmlydXMtYnJpZWZpbmctYmFjay10by1zY2hvb2wtY2hhb3MuaHRtbNIBXmh0dHBzOi8vd3d3Lm55dGltZXMuY29tLzIwMjIvMDEvMDMvYnJpZWZpbmcvY29yb25hdmlydXMtYnJpZWZpbmctYmFjay10by1zY2hvb2wtY2hhb3MuYW1wLmh0bWw?oc=5" >Coronavirus Briefing: Back-to-school chaos</a>  The New York Times</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 7:41 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMibGh0dHBzOi8vYXBuZXdzLmNvbS9hcnRpY2xlL2Nvcm9uYXZpcnVzLXBhbmRlbWljLXRyYXZlbC1mbGlnaHQtY2FuY2VsbGF0aW9ucy1iZWQzYjQ5MWVmOGRmZDc3OGFjNjEyZTM1YWRkNzVmYtIBAA?oc=5">Thousands of flights canceled, delayed at start of workweek - Associated Press</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMibGh0dHBzOi8vYXBuZXdzLmNvbS9hcnRpY2xlL2Nvcm9uYXZpcnVzLXBhbmRlbWljLXRyYXZlbC1mbGlnaHQtY2FuY2VsbGF0aW9ucy1iZWQzYjQ5MWVmOGRmZDc3OGFjNjEyZTM1YWRkNzVmYtIBAA?oc=5" >Thousands of flights canceled, delayed at start of workweek</a>  Associated Press</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9bmhoTHZkX2xWa3PSAQA?oc=5" >Mass Flight Cancellations During Post-Holiday Travel Rush</a>  NBC News</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMigQFodHRwczovL3d3dy50cmF2ZWxwdWxzZS5jb20vbmV3cy9haXJsaW5lcy9haXJsaW5lLWNhbmNlbGxhdGlvbnMtY29udGludWUtdG8tcmlzZS1idXQtc28tZG8tbnVtYmVyLW9mLWZsaWVycy1hbmQtc3RvY2stcHJpY2VzLmh0bWzSAQA?oc=5" >Airline Cancellations Continue to Rise, but So Do Number of Fliers and Stock Prices</a>  TravelPulse</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiWmh0dHBzOi8vd3d3Lndpc2h0di5jb20vbmV3cy9sb2NhbC1uZXdzL2Fub3RoZXItNDQtZmxpZ2h0cy1jYW5jZWxlZC1hdC1pbmR5LWFpcnBvcnQtbW9uZGF5L9IBAA?oc=5" >Another 44 flights canceled at Indy airport Monday</a>  WISHTV.com</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiTWh0dHBzOi8vd3d3Lm55dGltZXMuY29tLzIwMjIvMDEvMDMvYnVzaW5lc3MvYWlybGluZXMtZmxpZ2h0LWNhbmNlbGF0aW9ucy5odG1s0gEA?oc=5" >More Than 3,000 Flights Are Canceled on Monday</a>  The New York Times</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 7:30 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiJGh0dHBzOi8vd3d3LmJiYy5jb20vbmV3cy91ay01OTg2MTgzMdIBKGh0dHBzOi8vd3d3LmJiYy5jb20vbmV3cy91ay01OTg2MTgzMS5hbXA?oc=5">Prince Andrew accuser's 2009 deal with Jeffrey Epstein made public - BBC News</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiJGh0dHBzOi8vd3d3LmJiYy5jb20vbmV3cy91ay01OTg2MTgzMdIBKGh0dHBzOi8vd3d3LmJiYy5jb20vbmV3cy91ay01OTg2MTgzMS5hbXA?oc=5" >Prince Andrew accuser's 2009 deal with Jeffrey Epstein made public</a>  BBC News</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiWGh0dHBzOi8vd3d3LmNubi5jb20vMjAyMi8wMS8wMy91cy92aXJnaW5pYS1naXVmZnJlLWplZmZyZXktZXBzdGVpbi1zZXR0bGVtZW50L2luZGV4Lmh0bWzSAQA?oc=5" >Prince Andrew accuser Virginia Roberts Giuffre's 2009 settlement with Jeffrey Epstein released</a>  CNN</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMibmh0dHBzOi8vd3d3LmZveG5ld3MuY29tL3VzL2plZmZyZXktZXBzdGVpbnMtc2VjcmV0LTUwMGstc2V0dGxlbWVudC1hY2N1c2VyLXJlbGVhc2VkLXByaW5jZS1hbmRyZXctcmFwZS1sYXdzdWl00gEA?oc=5" >Jeffrey Epstein's secret $500K settlement with accuser released in Prince Andrew's sex abuse suit</a>  Fox News</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiigFodHRwczovL3d3dy50aGVkYWlseWJlYXN0LmNvbS9qZWZmcmV5LWVwc3RlaW5zLXNlY3JldC1zZXR0bGVtZW50LXdpdGgtcmFwZS1hY2N1c2VyLXZpcmdpbmlhLWdpdWZmcmUtZmluYWxseS1yZXZlYWxlZC1pbi1wcmluY2UtYW5kcmV3LXN1aXTSAQA?oc=5" >Epstein's Secret Settlement With Rape Accuser Virginia Giuffre Finally Revealed</a>  The Daily Beast</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiXmh0dHBzOi8vd3d3LnRoZWd1YXJkaWFuLmNvbS91cy1uZXdzLzIwMjIvamFuLzAzL2plZmZyZXktZXBzdGVpbi1wcmluY2UtYW5kcmV3LXZpcmdpbmlhLWdpdWZmcmXSAQA?oc=5" >Prince Andrew accuser Virginia Giuffre's legal deal with Jeffrey Epstein released</a>  The Guardian</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 7:10 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiYmh0dHBzOi8vd3d3LmNubi5jb20vMjAyMi8wMS8wMy9zcG9ydC9hbnRvbmlvLWJyb3duLWJydWNlLWFyaWFucy10YW1wYS1iYXktYnVjcy1zcHQtaW50bC9pbmRleC5odG1s0gEA?oc=5">Tampa Bay Buccaneers head coach Bruce Arians says he wishes Antonio Brown well - CNN</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiYmh0dHBzOi8vd3d3LmNubi5jb20vMjAyMi8wMS8wMy9zcG9ydC9hbnRvbmlvLWJyb3duLWJydWNlLWFyaWFucy10YW1wYS1iYXktYnVjcy1zcHQtaW50bC9pbmRleC5odG1s0gEA?oc=5" >Tampa Bay Buccaneers head coach Bruce Arians says he wishes Antonio Brown well</a>  CNN</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMieWh0dHBzOi8vc3BvcnRzLnlhaG9vLmNvbS9yZXBvcnQtYW50b25pby1icm93bi1jbGFpbXMtYW5rbGUtaW5qdXJ5LXByZXZlbnRlZC1oaW0tZnJvbS1yZS1lbnRlcmluZy1idWNzLWdhbWUtMTQzMjUzODY2Lmh0bWzSAQA?oc=5" >Report: Antonio Brown claims ankle injury prevented him from re-entering Bucs game</a>  Yahoo Sports</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMigQFodHRwczovL3d3dy5tc24uY29tL2VuLXVzL3Nwb3J0cy9uZmwvb3Bpbmlvbi10b20tYnJhZHktc2F5cy1hbnRvbmlvLWJyb3duLW5lZWRzLW91ci1jb21wYXNzaW9uLWlzLWhlLXJpZ2h0L2FyLUFBU29tSXM_bGk9QkIxNW1zNXHSAQA?oc=5" >Opinion: Tom Brady says Antonio Brown needs our compassion. Is he right?</a>  msnNOW</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiOGh0dHBzOi8vd3d3Lm1pYW1paGVyYWxkLmNvbS9zcG9ydHMvYXJ0aWNsZTI1NzAyNTI0Ny5odG1s0gE4aHR0cHM6Ly9hbXAubWlhbWloZXJhbGQuY29tL3Nwb3J0cy9hcnRpY2xlMjU3MDI1MjQ3Lmh0bWw?oc=5" >Brady, Buccaneers thriving despite losing big-name receivers</a>  Miami Herald</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiS2h0dHBzOi8vd3d3Lndhc2hpbmd0b25wb3N0LmNvbS9zcG9ydHMvMjAyMi8wMS8wMi9hbnRvbmlvLWJyb3duLW5mbC1jaGFuY2VzL9IBAA?oc=5" >Analysis | Antonio Brown walked away on his own terms Sunday. That should embarrass the NFL.</a>  The Washington Post</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 7:04 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiX2h0dHBzOi8vd3d3Lm55dGltZXMuY29tLzIwMjIvMDEvMDMvdGVjaG5vbG9neS9wZXJzb25hbHRlY2gvYmxhY2tiZXJyeS1kZXZpY2VzLXN0b3Atd29ya2luZy5odG1s0gEA?oc=5">BlackBerry Ends Service; Devices Will Stop Working January 4 - The New York Times</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiX2h0dHBzOi8vd3d3Lm55dGltZXMuY29tLzIwMjIvMDEvMDMvdGVjaG5vbG9neS9wZXJzb25hbHRlY2gvYmxhY2tiZXJyeS1kZXZpY2VzLXN0b3Atd29ya2luZy5odG1s0gEA?oc=5" >BlackBerry Ends Service; Devices Will Stop Working January 4</a>  The New York Times</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiV2h0dHBzOi8vd3d3Lm5wci5vcmcvMjAyMi8wMS8wMy8xMDY5OTM4NzI3L2JsYWNrYmVycnktcGhvbmVzLXdpbGwtc3RvcC13b3JraW5nLWphbnVhcnktNNIBAA?oc=5" >Classic BlackBerry devices will stop working on Jan. 4</a>  NPR</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9aTRGdGhsYUFReDDSAQA?oc=5" >RIP Blackberry: Classic phones won't work after tomorrow</a>  WTHR</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiKWh0dHBzOi8vdGhlaHVzdGxlLmNvLzAxMDMyMDIyLWJsYWNrYmVycnkv0gEpaHR0cHM6Ly90aGVodXN0bGUuY28vMDEwMzIwMjItYmxhY2tiZXJyeS8?oc=5" >How did BlackBerry fail?</a>  The Hustle</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiWWh0dHBzOi8vd3d3LnRoZWd1YXJkaWFuLmNvbS90ZWNobm9sb2d5LzIwMjIvamFuLzAzL2JsYWNrYmVycnktZGlzY29udGludWUtc2VydmljZS1jbGFzc2lj0gEA?oc=5" >BlackBerry signals end of an era as it prepares to pull plug on classic phones</a>  The Guardian</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 6:56 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiTGh0dHBzOi8vd3d3LnN0ZWVsZXJzLmNvbS9uZXdzL3N0ZWVsZXJzLWluYWN0aXZlcy1mb3Itd2Vlay0xNy12cy1icm93bnMteDA1MDTSAQA?oc=5">Steelers inactives for Week 17 vs. Browns - Steelers.com</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiTGh0dHBzOi8vd3d3LnN0ZWVsZXJzLmNvbS9uZXdzL3N0ZWVsZXJzLWluYWN0aXZlcy1mb3Itd2Vlay0xNy12cy1icm93bnMteDA1MDTSAQA?oc=5" >Steelers inactives for Week 17 vs. Browns</a>  Steelers.com</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMie2h0dHBzOi8vc3BvcnRzLnlhaG9vLmNvbS90aGUtZGFpbHktc3dlYXQtdGhlLWJyb3ducy13ZXJlLWVsaW1pbmF0ZWQtYW5kLXBvaW50LXNwcmVhZC12cy1zdGVlbGVycy1tb3ZlZC1hLWxvdC0xNDEwNDg1NTMuaHRtbNIBAA?oc=5" >The Daily Sweat: The Browns were eliminated, and point spread vs. Steelers moved a lot</a>  Yahoo Sports</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMikgFodHRwczovL3d3dy5hd2VzZW1vLmNvbS9vZGRzL21vbmRheS1uaWdodC1mb290YmFsbC1uZmwtYmVzdC1iZXRzLXRocmVlLWVhc3ktcGlja3MtcHJlZGljdGlvbnMtcHJvcHMtb2Rkcy1tbmYtYnJvd25zLXN0ZWVsZXJzLXRvbmlnaHQtd2Vlay0xNy0yMDIyL9IBAA?oc=5" >3 QUICK &amp; EASY Betting Picks Tonight for Browns vs. Steelers Week 17 NFL Monday Night Football</a>  Awesemo.com</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMibGh0dHBzOi8vdHJpYmxpdmUuY29tL3Nwb3J0cy9qLWMtaGFzc2VuYXVlci1nZXRzLXN0YXJ0LWF0LWNlbnRlci1vdmVyLWtlbmRyaWNrLWdyZWVuLWluLXN0ZWVsZXJzLWhvbWUtZmluYWxlL9IBAA?oc=5" >J.C. Hassenauer gets start at center over Kendrick Green in Steelers' home finale</a>  TribLIVE</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiRWh0dHBzOi8vd3d3LnZzaW4uY29tL2Jlc3QtbW9uZGF5LW5pZ2h0LWZvb3RiYWxsLWJldHMtc3RlZWxlcnMtYnJvd25zL9IBAA?oc=5" >Best Monday Night Football bets: Steelers-Browns - VSiN Exclusive News - News</a>  VSiN</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 6:53 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiZmh0dHBzOi8vYXBuZXdzLmNvbS9hcnRpY2xlL2VsZWN0aW9ucy12b3Rpbmctdm90aW5nLXJpZ2h0cy1maWxpYnVzdGVycy04NzAzNzc4NzQ2NzNjZDFkMjUxMzAwODE0ZmYxMDdjZdIBAA?oc=5">Schumer: Senate to vote on filibuster change on voting bill - Associated Press</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiZmh0dHBzOi8vYXBuZXdzLmNvbS9hcnRpY2xlL2VsZWN0aW9ucy12b3Rpbmctdm90aW5nLXJpZ2h0cy1maWxpYnVzdGVycy04NzAzNzc4NzQ2NzNjZDFkMjUxMzAwODE0ZmYxMDdjZdIBAA?oc=5" >Schumer: Senate to vote on filibuster change on voting bill</a>  Associated Press</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMi0AFodHRwczovL3d3dy53YXNoaW5ndG9ucG9zdC5jb20vcG9saXRpY3Mvc2NodW1lci1zYXlzLXNlbmF0ZS13aWxsLXZvdGUtYnktamFuLTE3LW9uLWNoYW5naW5nLXJ1bGVzLWlmLWdvcC1jb250aW51ZXMtdG8tYmxvY2stdm90aW5nLXJpZ2h0cy1sZWdpc2xhdGlvbi8yMDIyLzAxLzAzLzQ1MzYxOGM0LTZjYTctMTFlYy1iOWZjLWIzOTRkNTkyYTdhNl9zdG9yeS5odG1s0gEA?oc=5" >Schumer says Senate will vote by Jan. 17 on changing rules if GOP continues to block voting rights legislation</a>  The Washington Post</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiS2h0dHBzOi8vbmV3cy55YWhvby5jb20vc2NodW1lci10aHJlYXRlbnMtbnVrZS1maWxpYnVzdGVyLWdvcC0yMDQ4NTEwNDQuaHRtbNIBU2h0dHBzOi8vbmV3cy55YWhvby5jb20vYW1waHRtbC9zY2h1bWVyLXRocmVhdGVucy1udWtlLWZpbGlidXN0ZXItZ29wLTIwNDg1MTA0NC5odG1s?oc=5" >Schumer Threatens to Nuke Filibuster If GOP Stands Ground on Voting Bill</a>  Yahoo News</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiWmh0dHBzOi8vd3d3LmNubi5jb20vMjAyMi8wMS8wMy9wb2xpdGljcy9zY2h1bWVyLWZpbGlidXN0ZXItcnVsZXMtbWFuY2hpbi1zaW5lbWEvaW5kZXguaHRtbNIBAA?oc=5" >Schumer announces vote to change filibuster rules but faces resistance from Manchin and Sinema</a>  CNN</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMicmh0dHBzOi8vd3d3Lm5iY25ld3MuY29tL3BvbGl0aWNzL2NvbmdyZXNzL3NjaHVtZXItY2FsbHMtZGVtb2NyYWN5LXJlZm9ybXMtcHJldmVudC1tb3JlLWphbi02LXN0eWxlLWV2ZW50cy1uMTI4Njg1NNIBAA?oc=5" >Schumer calls for 'democracy reforms' to prevent more Jan. 6-style events</a>  NBC News</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 6:48 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiVmh0dHBzOi8vd3d3Lm55dGltZXMuY29tLzIwMjIvMDEvMDMvbnlyZWdpb24vbmV3LXlvcmstcmVkaXN0cmljdGluZy1nZXJyeW1hbmRlcmluZy5odG1s0gEA?oc=5">Odds of Gerrymandering Grow in New York as Redistricting Panel Falters - The New York Times</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiVmh0dHBzOi8vd3d3Lm55dGltZXMuY29tLzIwMjIvMDEvMDMvbnlyZWdpb24vbmV3LXlvcmstcmVkaXN0cmljdGluZy1nZXJyeW1hbmRlcmluZy5odG1s0gEA?oc=5" >Odds of Gerrymandering Grow in New York as Redistricting Panel Falters</a>  The New York Times</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9bm1heGxyVzFjRTTSAQA?oc=5" >NY redistricting fight moves to state Legislature after commission fails to agree on new map</a>  PIX11 News</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiV2h0dHBzOi8vZ290aGFtaXN0LmNvbS9uZXdzL25ldy15b3Jrcy1pbmRlcGVuZGVudC1yZWRpc3RyaWN0aW5nLXByb2Nlc3MtcmVhY2hlcy1ncmlkbG9ja9IBAA?oc=5" >New York's Independent Redistricting Process Reaches Gridlock</a>  Gothamist</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMidmh0dHBzOi8vd3d3LnN5cmFjdXNlLmNvbS9wb2xpdGljcy8yMDIyLzAxL255LXBhbmVsLXdhbnRzLXRvLW1lcmdlLWRpc3RyaWN0cy1vZi1nb3AtcmVwcy1qb2huLWthdGtvLWNsYXVkaWEtdGVubmV5Lmh0bWzSAQA?oc=5" >NY panel wants to merge districts of GOP Reps. John Katko, Claudia Tenney</a>  syracuse.com</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMie2h0dHBzOi8vd3d3LndrdHYuY29tL2NvbnRlbnQvbmV3cy9OZXctWW9ya3MtaW5kZXBlbmRlbnQtY29tbWlzc2lvbi1jYW5ub3QtY29tZS10by1hZ3JlZW1lbnQtb24tcmVkaXN0cmljdGluZy01NzYwMDM4OTEuaHRtbNIBAA?oc=5" >New York's independent commission cannot come to agreement on redistricting</a>  WKTV</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 6:33 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiaGh0dHBzOi8vd3d3LmNuYmMuY29tLzIwMjIvMDEvMDMvYXBwbGVzLTMtdHJpbGxpb24tbWFya2V0LWNhcC1zaG93cy12YWx1ZS1vZi1zaGFyZS1idXliYWNrcy1kaXZpZGVuZC5odG1s0gEA?oc=5">Apple's rise to $3 trillion market cap shows the value of its massive share buybacks - CNBC</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiaGh0dHBzOi8vd3d3LmNuYmMuY29tLzIwMjIvMDEvMDMvYXBwbGVzLTMtdHJpbGxpb24tbWFya2V0LWNhcC1zaG93cy12YWx1ZS1vZi1zaGFyZS1idXliYWNrcy1kaXZpZGVuZC5odG1s0gEA?oc=5" >Apple's rise to $3 trillion market cap shows the value of its massive share buybacks</a>  CNBC</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9TWFGYlRieTdrdjTSAQA?oc=5" >Apple Makes History as Rally Results in $3 Trillion Market Value</a>  Bloomberg Technology</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiYmh0dHBzOi8vd3d3LmNuYmMuY29tLzIwMjIvMDEvMDMvYXBwbGUtYmVjb21lcy1maXJzdC11cy1jb21wYW55LXRvLXJlYWNoLTMtdHJpbGxpb24tbWFya2V0LWNhcC5odG1s0gEA?oc=5" >Apple becomes first U.S. company to reach $3 trillion market cap</a>  CNBC</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiY2h0dHBzOi8vd3d3LmJsb29tYmVyZy5jb20vb3Bpbmlvbi9hcnRpY2xlcy8yMDIyLTAxLTAzL2FyZS1pbnZlc3RvcnMtcHV0dGluZy10b28tbXVjaC1mYWl0aC1pbi1hcHBsZdIBAA?oc=5" >Are Investors Putting Too Much Faith in Apple?</a>  Bloomberg</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiWmh0dHBzOi8vd3d3LmNubi5jb20vMjAyMi8wMS8wMy9pbnZlc3RpbmcvYXBwbGUtdGhyZWUtdHJpbGxpb24tZG9sbGFyLW1hcmtldC1jYXAvaW5kZXguaHRtbNIBAA?oc=5" >Apple has become the world's first $3 trillion company</a>  CNN</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 6:12 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMidWh0dHBzOi8vd3d3LmRhaWx5bWFpbC5jby51ay90dnNob3diaXovYXJ0aWNsZS0xMDM2NTk3NS9CZXR0eS1XaGl0ZXMtd29yZC1tb3V0aC1jYWxsaW5nLWxhdGUtaHVzYmFuZC1BbGxlbi1MdWRkZW4uaHRtbNIBeWh0dHBzOi8vd3d3LmRhaWx5bWFpbC5jby51ay90dnNob3diaXovYXJ0aWNsZS0xMDM2NTk3NS9hbXAvQmV0dHktV2hpdGVzLXdvcmQtbW91dGgtY2FsbGluZy1sYXRlLWh1c2JhbmQtQWxsZW4tTHVkZGVuLmh0bWw?oc=5">Betty White's 'very last word out of her mouth' was calling for late husband Allen Ludden - Daily Mail</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMidWh0dHBzOi8vd3d3LmRhaWx5bWFpbC5jby51ay90dnNob3diaXovYXJ0aWNsZS0xMDM2NTk3NS9CZXR0eS1XaGl0ZXMtd29yZC1tb3V0aC1jYWxsaW5nLWxhdGUtaHVzYmFuZC1BbGxlbi1MdWRkZW4uaHRtbNIBeWh0dHBzOi8vd3d3LmRhaWx5bWFpbC5jby51ay90dnNob3diaXovYXJ0aWNsZS0xMDM2NTk3NS9hbXAvQmV0dHktV2hpdGVzLXdvcmQtbW91dGgtY2FsbGluZy1sYXRlLWh1c2JhbmQtQWxsZW4tTHVkZGVuLmh0bWw?oc=5" >Betty White's 'very last word out of her mouth' was calling for late husband Allen Ludden</a>  Daily Mail</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMifGh0dHBzOi8vd3d3LnlhaG9vLmNvbS9lbnRlcnRhaW5tZW50L2JldHR5LXdoaXRlLWNhdXNlLW9mLWRlYXRoLW5hdHVyYWwtY2F1c2VzLW5vdC1jb3ZpZC1ib29zdGVyLWNvbXBsaWNhdGlvbnMtMjIzMTQ3MjY5Lmh0bWzSAQA?oc=5" >Betty White 'died of natural causes,' not COVID booster complications, says agent: 'Her death should not be politicized'</a>  Yahoo Entertainment</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiU2h0dHBzOi8vd3d3LmNubi5jb20vMjAyMi8wMS8wMi9vcGluaW9ucy9iZXR0eS13aGl0ZS1hY3RpdmlzbS1sZWdhY3kteXVrby9pbmRleC5odG1s0gEA?oc=5" >Betty White's legacy goes far beyond the screen</a>  CNN</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMifWh0dHBzOi8vd3d3LmRhaWx5bWFpbC5jby51ay90dnNob3diaXovYXJ0aWNsZS0xMDM2NTc1MS9CZXR0eS1XaGl0ZS1hZ2VudC1kZW5pZXMtcnVtb3ItZGVhdGgtcmVsYXRlZC1nZXR0aW5nLWJvb3N0ZXItc2hvdC5odG1s0gEA?oc=5" >Betty White agent denies rumor that her death was related to getting a booster shot</a>  Daily Mail</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiTGh0dHBzOi8vd3d3LnlhaG9vLmNvbS9lbnRlcnRhaW5tZW50L2JldHR5LXdoaXRlLWhhZC1iaWctY3J1c2gtMTgxMDU0MjQ0Lmh0bWzSAVRodHRwczovL3d3dy55YWhvby5jb20vYW1waHRtbC9lbnRlcnRhaW5tZW50L2JldHR5LXdoaXRlLWhhZC1iaWctY3J1c2gtMTgxMDU0MjQ0Lmh0bWw?oc=5" >Betty White had a big crush on Robert Redford. And he says the feeling was mutual</a>  Yahoo Entertainment</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 5:58 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiemh0dHBzOi8vd3d3LmxhdGltZXMuY29tL2NhbGlmb3JuaWEvc3RvcnkvMjAyMi0wMS0wMy9sYS11bmlmaWVkLW1hbmRhdG9yeS1jb3ZpZC10ZXN0aW5nLWJlZm9yZS1zY2hvb2wtcmVzdW1lcy1vbWljcm9uLXN1cmdl0gEA?oc=5">L.A. Unified orders COVID-19 testing before classes resume - Los Angeles Times</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiemh0dHBzOi8vd3d3LmxhdGltZXMuY29tL2NhbGlmb3JuaWEvc3RvcnkvMjAyMi0wMS0wMy9sYS11bmlmaWVkLW1hbmRhdG9yeS1jb3ZpZC10ZXN0aW5nLWJlZm9yZS1zY2hvb2wtcmVzdW1lcy1vbWljcm9uLXN1cmdl0gEA?oc=5" >L.A. Unified orders COVID-19 testing before classes resume</a>  Los Angeles Times</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9NWJWN3VkRWZOSzjSAQA?oc=5" >Millions return to school despite COVID surge</a>  CBS Evening News</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiiAFodHRwczovL3d3dy5jbGlja29uZGV0cm9pdC5jb20vbmV3cy9sb2NhbC8yMDIyLzAxLzAzL3BhcmVudHMtaGF2ZS1jb25jZXJucy1hcy1zdHVkZW50cy1yZXR1cm4tdG8taW4tcGVyc29uLWxlYXJuaW5nLWFmdGVyLWhvbGlkYXktYnJlYWsv0gEA?oc=5" >Michigan parents have concerns as students return to in-person learning after holiday break</a>  WDIV ClickOnDetroit</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiqwFodHRwczovL3d3dy53ZmFhLmNvbS9hcnRpY2xlL25ld3MvZWR1Y2F0aW9uL3NjaG9vbHMvbm9ydGgtdGV4YXMtc2Nob29sLWRpc3RyaWN0cy1yZXR1cm5pbmctdG8tY2xhc3MtZnJvbS1ob2xpZGF5LWJyZWFrLWNvdmlkLXN1cmdlLzI4Ny1iOTg1MTA5Yi00YWM0LTRmNTItYTc3Mi1mYjU3MDA2NjY2NDbSAa8BaHR0cHM6Ly93d3cud2ZhYS5jb20vYW1wL2FydGljbGUvbmV3cy9lZHVjYXRpb24vc2Nob29scy9ub3J0aC10ZXhhcy1zY2hvb2wtZGlzdHJpY3RzLXJldHVybmluZy10by1jbGFzcy1mcm9tLWhvbGlkYXktYnJlYWstY292aWQtc3VyZ2UvMjg3LWI5ODUxMDliLTRhYzQtNGY1Mi1hNzcyLWZiNTcwMDY2NjY0Ng?oc=5" >Here's what North Texas school districts are saying about returning to class from holiday break with COVID cases surging</a>  WFAA.com</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiX2h0dHBzOi8vYWJjNy5jb20vbG9zLWFuZ2VsZXMtc2Nob29scy1sYXVzZC1jb3ZpZC1ydWxlcy1mcmVlLWNvcm9uYXZpcnVzLXRlc3Rpbmctc2l0ZXMvMTE0MjEzMjUv0gFjaHR0cHM6Ly9hYmM3LmNvbS9hbXAvbG9zLWFuZ2VsZXMtc2Nob29scy1sYXVzZC1jb3ZpZC1ydWxlcy1mcmVlLWNvcm9uYXZpcnVzLXRlc3Rpbmctc2l0ZXMvMTE0MjEzMjUv?oc=5" >LAUSD families rush to get students tested for COVID before classes resume; centers reopened Monday with extended hours</a>  KABC-TV</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 5:26 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiSGh0dHBzOi8vd3d3Lndzai5jb20vYXJ0aWNsZXMvdGVzbGEtc3RvY2stanVtcHMtdG8tc3RhcnQtMjAyMi0xMTY0MTIzNTAyONIBAA?oc=5">Tesla Stock Jumps to Start 2022 - The Wall Street Journal</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiSGh0dHBzOi8vd3d3Lndzai5jb20vYXJ0aWNsZXMvdGVzbGEtc3RvY2stanVtcHMtdG8tc3RhcnQtMjAyMi0xMTY0MTIzNTAyONIBAA?oc=5" >Tesla Stock Jumps to Start 2022</a>  The Wall Street Journal</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9RG84Yi12N2tDZG_SAQA?oc=5" >Tesla reports record number of vehicle deliveries in Q4 at 308600</a>  CNBC Television</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMieWh0dHBzOi8vd3d3LmludmVzdGluZy5jb20vbmV3cy9zdG9jay1tYXJrZXQtbmV3cy9ldi1kZWxpdmVyeS1udW1iZXJzLWEtMjAyMS1lbmNvcmUtb2lsLWpvbHQtLXdoYXRzLW1vdmluZy1tYXJrZXRzLTI3Mjg4MzLSAQA?oc=5" >EV Delivery Numbers, a 2021 Encore, Oil Jolt - What's Moving Markets By Investing.com</a>  Investing.com</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiaWh0dHBzOi8vd3d3LmNuYmMuY29tLzIwMjIvMDEvMDMvdGVzbGEtc3RvY2stanVtcHMtYWZ0ZXItcmVwb3J0aW5nLXJlY29yZC12ZWhpY2xlLWRlbGl2ZXJpZXMtZm9yLTIwMjEuaHRtbNIBAA?oc=5" >Tesla stock closes up 13% after reporting record vehicle deliveries for 2021</a>  CNBC</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9ckQtRHl4ZTVxTk3SAQA?oc=5" >Tesla shares surge after company hits record vehicle deliveries in 2021</a>  CNBC Television</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 5:25 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMibWh0dHBzOi8vd3d3LmtzYncuY29tL2FydGljbGUvbW9udGVyZXktY2FsaWZvcm5pYS10d2lucy1ib3JuLWluLWRpZmZlcmVudC15ZWFycy1qdXN0LTE1LW1pbnV0ZXMtYXBhcnQvMzg2NTgxMTjSAQA?oc=5">Monterey County twins born in different years just 15 minutes apart - KSBW Monterey</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMibWh0dHBzOi8vd3d3LmtzYncuY29tL2FydGljbGUvbW9udGVyZXktY2FsaWZvcm5pYS10d2lucy1ib3JuLWluLWRpZmZlcmVudC15ZWFycy1qdXN0LTE1LW1pbnV0ZXMtYXBhcnQvMzg2NTgxMTjSAQA?oc=5" >Monterey County twins born in different years just 15 minutes apart</a>  KSBW Monterey</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiWWh0dHBzOi8vd3d3LnExM2ZveC5jb20vbmV3cy9jYWxpZm9ybmlhLXR3aW5zLWJvcm4tMTUtbWludXRlcy1hcGFydC1idXQtaW4tZGlmZmVyZW50LXllYXJz0gFdaHR0cHM6Ly93d3cucTEzZm94LmNvbS9uZXdzL2NhbGlmb3JuaWEtdHdpbnMtYm9ybi0xNS1taW51dGVzLWFwYXJ0LWJ1dC1pbi1kaWZmZXJlbnQteWVhcnMuYW1w?oc=5" >California twins born 15 minutes apart, but in different years</a>  Q13 FOX (Seattle)</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9ZkpfZkpwSW4wb1nSAQA?oc=5" >Proud parents: Arizona's first babies of 2022 born in Tucson</a>  azfamily powered by 3TV &amp; CBS5AZ</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiTWh0dHBzOi8vd3d3LmZveG5ld3MuY29tL2xpZmVzdHlsZS90d2lucy1ib3JuLWRpZmZlcmVudC15ZWFycy0xNS1taW51dGVzLWFwYXJ00gEA?oc=5" >Twins born in different years, 15 minutes apart: '1 in 2 million chance'</a>  Fox News</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMinQFodHRwczovL3d3dy50YWxsYWhhc3NlZS5jb20vc3RvcnkvbmV3cy8yMDIyLzAxLzAzL2ZpcnN0LWJhYmllcy1ib3JuLXRhbGxhaGFzc2VlLWhvc3BpdGFscy0yMDIyLWNhcGl0YWwtcmVnaW9uYWwtbWVtb3JpYWwtaGVhbHRoY2FyZS1uZXdib3JuLWNoaWxkLzkwNzY4NjUwMDIv0gEA?oc=5" >Meet Kaisleigh and Kanelo: Tallahassee hospitals welcome first babies of 2022</a>  Tallahassee Democrat</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 5:23 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiaGh0dHBzOi8vYWJjbmV3cy5nby5jb20vVVMvZWxkZXN0LXRydW1wLWNoaWxkcmVuLWNvbXBseS1zdWJwb2VuYXMteW9yay1hdHRvcm5leS1nZW5lcmFsL3N0b3J5P2lkPTgyMDUyNzMy0gFsaHR0cHM6Ly9hYmNuZXdzLmdvLmNvbS9hbXAvVVMvZWxkZXN0LXRydW1wLWNoaWxkcmVuLWNvbXBseS1zdWJwb2VuYXMteW9yay1hdHRvcm5leS1nZW5lcmFsL3N0b3J5P2lkPTgyMDUyNzMy?oc=5">Eldest Trump children won't comply with subpoenas from New York attorney general - ABC News</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiaGh0dHBzOi8vYWJjbmV3cy5nby5jb20vVVMvZWxkZXN0LXRydW1wLWNoaWxkcmVuLWNvbXBseS1zdWJwb2VuYXMteW9yay1hdHRvcm5leS1nZW5lcmFsL3N0b3J5P2lkPTgyMDUyNzMy0gFsaHR0cHM6Ly9hYmNuZXdzLmdvLmNvbS9hbXAvVVMvZWxkZXN0LXRydW1wLWNoaWxkcmVuLWNvbXBseS1zdWJwb2VuYXMteW9yay1hdHRvcm5leS1nZW5lcmFsL3N0b3J5P2lkPTgyMDUyNzMy?oc=5" >Eldest Trump children won't comply with subpoenas from New York attorney general</a>  ABC News</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9eVJBVVFTSmlzSEHSAQA?oc=5" >Ivanka Trump and Donald Trump Jr. subpoenaed by NY AG</a>  CNN</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMigQFodHRwczovL3d3dy50aGVkYWlseWJlYXN0LmNvbS90cnVtcC1hbmQtaGlzLWNoaWxkcmVuLWRvbi1qci1hbmQtaXZhbmthLXJlZnVzZS10by1iZS1kZXBvc2VkLWluLW5ldy15b3JrLXRheC1kb2RnaW5nLWludmVzdGlnYXRpb27SAQA?oc=5" >Trump and His Children Refuse to Be Deposed in Tax Dodging Investigation</a>  The Daily Beast</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiXmh0dHBzOi8vd3d3Lm55dGltZXMuY29tLzIwMjIvMDEvMDMvbnlyZWdpb24vbGV0aXRpYS1qYW1lcy1pdmFua2EtZG9uYWxkLXRydW1wLWpyLXN1YnBvZW5hLmh0bWzSAQA?oc=5" >Letitia James Seeks to Question Trump Children in Fraud Inquiry</a>  The New York Times</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiQ2h0dHBzOi8vbmV3cy55YWhvby5jb20vZG9uYWxkLWpyLWl2YW5rYS10cnVtcC1yZWZ1c2UtMTgyODE0NTU0Lmh0bWzSAUtodHRwczovL25ld3MueWFob28uY29tL2FtcGh0bWwvZG9uYWxkLWpyLWl2YW5rYS10cnVtcC1yZWZ1c2UtMTgyODE0NTU0Lmh0bWw?oc=5" >Donald Jr. and Ivanka Trump refuse to comply with subpoena from NY attorney general</a>  Yahoo News</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 5:17 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMihgFodHRwczovL3d3dy5lc3BuLmNvbS9jb2xsZWdlLWZvb3RiYWxsL3N0b3J5L18vaWQvMzI5ODczMTUvcWItY2FsZWItd2lsbGlhbXMtZWxlY3RzLWVudGVyLXRyYW5zZmVyLXBvcnRhbC1rZWVwLW9rbGFob21hLWZvb3RiYWxsLW9wdGlvbtIBkwFodHRwczovL3d3dy5lc3BuLmNvbS9jb2xsZWdlLWZvb3RiYWxsL3N0b3J5L18vaWQvMzI5ODczMTUvcWItY2FsZWItd2lsbGlhbXMtZWxlY3RzLWVudGVyLXRyYW5zZmVyLXBvcnRhbC1rZWVwLW9rbGFob21hLWZvb3RiYWxsLW9wdGlvbj9wbGF0Zm9ybT1hbXA?oc=5">QB Caleb Williams elects to enter transfer portal but will keep Oklahoma football an option - ESPN</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMihgFodHRwczovL3d3dy5lc3BuLmNvbS9jb2xsZWdlLWZvb3RiYWxsL3N0b3J5L18vaWQvMzI5ODczMTUvcWItY2FsZWItd2lsbGlhbXMtZWxlY3RzLWVudGVyLXRyYW5zZmVyLXBvcnRhbC1rZWVwLW9rbGFob21hLWZvb3RiYWxsLW9wdGlvbtIBkwFodHRwczovL3d3dy5lc3BuLmNvbS9jb2xsZWdlLWZvb3RiYWxsL3N0b3J5L18vaWQvMzI5ODczMTUvcWItY2FsZWItd2lsbGlhbXMtZWxlY3RzLWVudGVyLXRyYW5zZmVyLXBvcnRhbC1rZWVwLW9rbGFob21hLWZvb3RiYWxsLW9wdGlvbj9wbGF0Zm9ybT1hbXA?oc=5" >QB Caleb Williams elects to enter transfer portal but will keep Oklahoma football an option</a>  ESPN</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9U21Ib1NZOUVSQjTSAQA?oc=5" >Caleb Williams to Enter Transfer Portal, Doesn't Rule Out Returning to Oklahoma | CBS Sports HQ</a>  CBS Sports HQ</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiaGh0dHBzOi8vd3d3LnNpLmNvbS9jb2xsZWdlL29rbGFob21hL2Zvb3RiYWxsL2NvbW1lbnRhcnktd2hhdHMtbmV4dC1mb3Itb2tsYWhvbWEtaWYtY2FsZWItd2lsbGlhbXMtbGVhdmVz0gFtaHR0cHM6Ly93d3cuc2kuY29tL2NvbGxlZ2Uvb2tsYWhvbWEvLmFtcC9mb290YmFsbC9jb21tZW50YXJ5LXdoYXRzLW5leHQtZm9yLW9rbGFob21hLWlmLWNhbGViLXdpbGxpYW1zLWxlYXZlcw?oc=5" >Commentary: What's Next for Oklahoma if Caleb Williams Leaves?</a>  CalBearsMaven</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiXGh0dHBzOi8vd3d3LmtvY28uY29tL2FydGljbGUvb3UtcXVhcnRlcmJhY2stY2FsZWItd2lsbGlhbXMtZW50ZXJpbmctdHJhbnNmZXItcG9ydGFsLzM4NjU4MzI10gEA?oc=5" >OU quarterback Caleb Williams entering transfer portal</a>  KOCO Oklahoma City</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMieGh0dHBzOi8vc3BvcnRzLnlhaG9vLmNvbS9va2xhaG9tYS1xYi1jYWxlYi13aWxsaWFtcy10by1leHBsb3JlLXRyYW5zZmVyLW9wdGlvbnMtY291bGQtcmVtYWluLXdpdGgtc29vbmVycy0yMTIxNTU5OTIuaHRtbNIBAA?oc=5" >Oklahoma QB Caleb Williams to explore transfer options, could remain with Sooners</a>  Yahoo Sports</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 5:08 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMibGh0dHBzOi8vd3d3Lndzai5jb20vYXJ0aWNsZXMvZnJhbmNlLXJlbGF4ZXMtcXVhcmFudGluZS1ydWxlcy1hcy1ldXJvcGUtYWRhcHRzLXRvLW9taWNyb25zLXNwcmVhZC0xMTY0MTIxNzA5N9IBAA?oc=5">Covid-19 Cases Soar to New Records in U.S. - The Wall Street Journal</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMibGh0dHBzOi8vd3d3Lndzai5jb20vYXJ0aWNsZXMvZnJhbmNlLXJlbGF4ZXMtcXVhcmFudGluZS1ydWxlcy1hcy1ldXJvcGUtYWRhcHRzLXRvLW9taWNyb25zLXNwcmVhZC0xMTY0MTIxNzA5N9IBAA?oc=5" >Covid-19 Cases Soar to New Records in U.S.</a>  The Wall Street Journal</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiWmh0dHBzOi8vd3d3LnRoZWd1YXJkaWFuLmNvbS91cy1uZXdzLzIwMjIvamFuLzAzL3VzLWNvdmlkLW9taWNyb24tY29yb25hdmlydXMtY2FzZXMtZmxvcmlkYdIBAA?oc=5" >Covid cases rise by 948% in Florida as Omicron drives huge wave across US</a>  The Guardian</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMieGh0dHBzOi8vd3d3LmphY2tzb252aWxsZS5jb20vc3RvcnkvbmV3cy8yMDIyLzAxLzAzL2NvdmlkLWZsb3JpZGEtb21pY3Jvbi1saXN0LXN0YXRlcy12aXJ1cy1zcHJlYWRpbmctZmFzdGVzdC85MDc2MjY1MDAyL9IBK2h0dHBzOi8vYW1wLmphY2tzb252aWxsZS5jb20vYW1wLzkwNzYyNjUwMDI?oc=5" >Omicron surge: Florida moves up on Top 10 list of states where COVID-19 is spreading the fastest</a>  The Florida Times-Union</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiQmh0dHBzOi8vd3d3Lm1pYW1paGVyYWxkLmNvbS9uZXdzL2Nvcm9uYXZpcnVzL2FydGljbGUyNTcwMTU0NzcuaHRtbNIBAA?oc=5" >Florida COVID update: State breaks another case record, and hospitalizations on the rise</a>  Miami Herald</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMicWh0dHBzOi8vd3d3LndmbGEuY29tL25ld3MvcG9say1jb3VudHkvY292aWQtMTktaG9zcGl0YWxpemF0aW9ucy1pbmNyZWFzZS1yYXBpZGx5LWluLXBvbGstY291bnR5LWFtaWQtZm91cnRoLXdhdmUv0gF1aHR0cHM6Ly93d3cud2ZsYS5jb20vbmV3cy9wb2xrLWNvdW50eS9jb3ZpZC0xOS1ob3NwaXRhbGl6YXRpb25zLWluY3JlYXNlLXJhcGlkbHktaW4tcG9say1jb3VudHktYW1pZC1mb3VydGgtd2F2ZS9hbXAv?oc=5" >COVID-19 hospitalizations increase 'rapidly' in Polk County amid fourth wave</a>  WFLA</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 4:49 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMicGh0dHBzOi8vd3d3LmNpbmN5anVuZ2xlLmNvbS8yMDIyLzEvMy8yMjg2NDI3Ny9iZW5nYWxzLWhpZ2hsaWdodHMtY2hpZWZzLXRvcC0xMC1wbGF5cy1jaW5jaW5uYXRpLWthbnNhcy1jaXR5LTIwMjLSAQA?oc=5">Bengals highlights vs Chiefs: The top 10 plays from Cincinnati's wild win over Kansas City - Cincy Jungle</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMicGh0dHBzOi8vd3d3LmNpbmN5anVuZ2xlLmNvbS8yMDIyLzEvMy8yMjg2NDI3Ny9iZW5nYWxzLWhpZ2hsaWdodHMtY2hpZWZzLXRvcC0xMC1wbGF5cy1jaW5jaW5uYXRpLWthbnNhcy1jaXR5LTIwMjLSAQA?oc=5" >Bengals highlights vs Chiefs: The top 10 plays from Cincinnati's wild win over Kansas City</a>  Cincy Jungle</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9QVFhVUNFZ25SNGPSAQA?oc=5" >Can Cincinnati Bengals' defense perform under playoff pressure? | Pro Football Talk | NBC Sports</a>  NBC Sports</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMitwFodHRwczovL3d3dy5jaW5jaW5uYXRpLmNvbS9zdG9yeS9zcG9ydHMvY29sdW1uaXN0cy9wYXVsLWRhdWdoZXJ0eS8yMDIyLzAxLzAyL25mbC13ZWVrLTE3LWNpbmNpbm5hdGktYmVuZ2Fscy1hdXRob3Itbm92ZWwtdnMta2MtY2hpZWZzLWFmYy1ub3J0aC13ZXN0LWNvbHVtbi1wbGF5b2ZmLXBpY3R1cmUvOTA3NDA3MjAwMi_SASlodHRwczovL2FtcC5jaW5jaW5uYXRpLmNvbS9hbXAvOTA3NDA3MjAwMg?oc=5" >Paul Daugherty: Bengals win over Chiefs so thick with plots, it should be a Netflix series</a>  Cincinnati.com</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiUGh0dHBzOi8vYXJyb3doZWFkYWRkaWN0LmNvbS8yMDIyLzAxLzAzL2tjLWNoaWVmcy1sb3RzLWJsYW1lLWFzc2lnbi1sb3NzLWJlbmdhbHMv0gEA?oc=5" >KC Chiefs have lots of blame to assign for frustrating loss to Bengals</a>  Arrowhead Addict</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9R3ByTVNBVDZFaknSAQA?oc=5" >Mathieu on calls: "I still feel we could've responded a lot better defensively."</a>  KCTV5 News</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 4:33 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiXmh0dHBzOi8vd3d3Lndhc2hpbmd0b25wb3N0LmNvbS9hcnRzLWVudGVydGFpbm1lbnQvMjAyMi8wMS8wMy9kYXZpZC1ib3dpZS1jYXRhbG9nLXdhcm5lci1tdXNpYy_SAQA?oc=5">David Bowie's estate sells his 'entire' songwriting catalogue to Warner Music - The Washington Post</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiXmh0dHBzOi8vd3d3Lndhc2hpbmd0b25wb3N0LmNvbS9hcnRzLWVudGVydGFpbm1lbnQvMjAyMi8wMS8wMy9kYXZpZC1ib3dpZS1jYXRhbG9nLXdhcm5lci1tdXNpYy_SAQA?oc=5" >David Bowie's estate sells his 'entire' songwriting catalogue to Warner Music</a>  The Washington Post</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiS2h0dHBzOi8vd3d3Lm55dGltZXMuY29tLzIwMjIvMDEvMDMvYXJ0cy9tdXNpYy9kYXZpZC1ib3dpZS1jYXRhbG9nLXNvbGQuaHRtbNIBAA?oc=5" >David Bowie Estate Sells Songwriting Catalog to Warner Music</a>  The New York Times</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiZ2h0dHBzOi8vdmFyaWV0eS5jb20vMjAyMi9tdXNpYy9uZXdzL2RhdmlkLWJvd2llLXB1Ymxpc2hpbmctY2F0YWxvZy1hY3F1aXJlZC13YXJuZXItY2hhcHBlbGwtMTIzNTE0NTk0MS_SAQA?oc=5" >David Bowie's Estate Sells His Publishing Catalog to Warner Chappell (EXCLUSIVE)</a>  Variety</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiamh0dHBzOi8vd3d3LmxhdGltZXMuY29tL2VudGVydGFpbm1lbnQtYXJ0cy9tdXNpYy9zdG9yeS8yMDIyLTAxLTAzL2RhdmlkLWJvd2llLXNlbGxzLXB1Ymxpc2hpbmctc29uZ3dyaXRpbmfSAQA?oc=5" >David Bowie estate sells publishing catalog for $250 million</a>  Los Angeles Times</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiPGh0dHBzOi8vd3d3LmphbWJhc2UuY29tL2FydGljbGUvZGF2aWQtYm93aWUtY2hhbm5lbC1zaXJpdXN4bdIBAA?oc=5" >SiriusXM Announces Limited-Run David Bowie Channel</a>  JamBase</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 4:26 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMie2h0dHBzOi8vd3d3LmtjcmEuY29tL2FydGljbGUvY292aWQtMTktY2FzZXMtaGl0LWEtbmV3LXJlY29yZC1pbi1zYWNyYW1lbnRvLWNvdW50eS1ob3NwaXRhbGl6YXRpb25zLXVwLTYyLWluLWEtd2Vlay8zODY1ODI0NtIBAA?oc=5">COVID-19 cases hit a new record in Sacramento County, hospitalizations up 62% in a week - KCRA Sacramento</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMie2h0dHBzOi8vd3d3LmtjcmEuY29tL2FydGljbGUvY292aWQtMTktY2FzZXMtaGl0LWEtbmV3LXJlY29yZC1pbi1zYWNyYW1lbnRvLWNvdW50eS1ob3NwaXRhbGl6YXRpb25zLXVwLTYyLWluLWEtd2Vlay8zODY1ODI0NtIBAA?oc=5" >COVID-19 cases hit a new record in Sacramento County, hospitalizations up 62% in a week</a>  KCRA Sacramento</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMihwFodHRwczovL3d3dy44bmV3c25vdy5jb20vbmV3cy9oZWFsdGgvY29yb25hdmlydXMtaGVhbHRoL25ldy1jbGFyay1jb3VudHktcmVwb3J0cy1yZWNvcmQtYnJlYWtpbmctY292aWQtMTktY2FzZXMtb3Zlci1uZXcteWVhcnMtd2Vla2VuZC_SAYsBaHR0cHM6Ly93d3cuOG5ld3Nub3cuY29tL25ld3MvaGVhbHRoL2Nvcm9uYXZpcnVzLWhlYWx0aC9uZXctY2xhcmstY291bnR5LXJlcG9ydHMtcmVjb3JkLWJyZWFraW5nLWNvdmlkLTE5LWNhc2VzLW92ZXItbmV3LXllYXJzLXdlZWtlbmQvYW1wLw?oc=5" >NEW: Clark County reports record-breaking COVID-19 cases over New Year's weekend</a>  KLAS - 8 News Now</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMieGh0dHBzOi8vd3d3LmFiYzEwLmNvbS9hcnRpY2xlL25ld3MvbG9jYWwvc2FjcmFtZW50by9zYWNyYW1lbnRvLWNvdmlkLWNhc2Utc3Bpa2UvMTAzLThkMTBjMTJiLTVhMDctNDg4NS1iNjViLWYxMDgyNGQ4MjdjONIBfGh0dHBzOi8vd3d3LmFiYzEwLmNvbS9hbXAvYXJ0aWNsZS9uZXdzL2xvY2FsL3NhY3JhbWVudG8vc2FjcmFtZW50by1jb3ZpZC1jYXNlLXNwaWtlLzEwMy04ZDEwYzEyYi01YTA3LTQ4ODUtYjY1Yi1mMTA4MjRkODI3Yzg?oc=5" >Sacramento area wraps up December 2021 with COVID-19 case spike</a>  ABC10.com KXTV</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMifWh0dHBzOi8va3RsYS5jb20vbmV3cy9sb2NhbC1uZXdzL2V4cGxvc2l2ZS10cmFuc21pc3Npb24tbC1hLWNvdW50eS1yZWNvcmRzLW5lYXJseS00NTAwMC1uZXctY292aWQtY2FzZXMtb3Zlci1ob2xpZGF5LXdlZWtlbmQv0gEA?oc=5" >'Explosive transmission': L.A. County records nearly 45,000 new COVID cases over holiday weekend</a>  KTLA Los Angeles</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiUmh0dHBzOi8vZGVhZGxpbmUuY29tLzIwMjIvMDEvbC1hLWNvdW50eS1jb3ZpZC0xOS1kZWF0aHMtcG9zaXRpdmUtY2FzZXMtMTIzNDkwMzY0OC_SAQA?oc=5" >L.A. County Reports Two New Covid-19 Deaths And 21,200 New Positive Cases</a>  Deadline</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 4:20 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiTWh0dHBzOi8vcGh5cy5vcmcvbmV3cy8yMDIyLTAxLWFzdHJvbm9tZXJzLW15c3RlcmlvdXMtZHVzdHktb3JiaXRpbmctc3Rhci5odG1s0gEA?oc=5">Astronomers find mysterious dusty object orbiting a star - Phys.org</a></font></h3>
      <p><font size="4"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiTWh0dHBzOi8vcGh5cy5vcmcvbmV3cy8yMDIyLTAxLWFzdHJvbm9tZXJzLW15c3RlcmlvdXMtZHVzdHktb3JiaXRpbmctc3Rhci5odG1s0gEA?oc=5" >Astronomers find mysterious dusty object orbiting a star</a>  Phys.org</li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 4:06 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMihgFodHRwczovL3d3dy51c2F0b2RheS5jb20vc3RvcnkvZW50ZXJ0YWlubWVudC90di8yMDIyLzAxLzAzL2tlbmFuLXRob21wc29uLWp1Z2dsaW5nLWhpcy1uYmMtc2l0Y29tLWFuZC1oaWdobHktZW1vdGlvbmFsLXNubC85MDgwNzcyMDAyL9IBAA?oc=5">Kenan Thompson on the 'highly emotional' 'SNL' and Season 2 of his NBC sitcom - USA TODAY</a></font></h3>
      <p><font size="4"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMihgFodHRwczovL3d3dy51c2F0b2RheS5jb20vc3RvcnkvZW50ZXJ0YWlubWVudC90di8yMDIyLzAxLzAzL2tlbmFuLXRob21wc29uLWp1Z2dsaW5nLWhpcy1uYmMtc2l0Y29tLWFuZC1oaWdobHktZW1vdGlvbmFsLXNubC85MDgwNzcyMDAyL9IBAA?oc=5" >Kenan Thompson on the 'highly emotional' 'SNL' and Season 2 of his NBC sitcom</a>  USA TODAY<b><a href="article.php?loc=US&a=https://news.google.com/stories/CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2p6Mk9qREJCRWpGS3VpNVBTVkt5Z0FQAQ?oc=5" ></a></b></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 3:56 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiV2h0dHBzOi8vd3d3LndtdXIuY29tL2FydGljbGUvbmVpZ2hib3JzLW1pc3NpbmctZ2lybC1tYW5jaGVzdGVyLWhvbWUtY29uZGl0aW9ucy8zODY1NzA3NtIBAA?oc=5">Neighbors complained about home where missing NH girl lived - WMUR Manchester</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiV2h0dHBzOi8vd3d3LndtdXIuY29tL2FydGljbGUvbmVpZ2hib3JzLW1pc3NpbmctZ2lybC1tYW5jaGVzdGVyLWhvbWUtY29uZGl0aW9ucy8zODY1NzA3NtIBAA?oc=5" >Neighbors complained about home where missing NH girl lived</a>  WMUR Manchester</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiSGh0dHBzOi8vd3d3LmZveG5ld3MuY29tL3VzL21pc3NpbmctbmV3LWhhbXBzaGlyZS1naXJsLWhhcm1vbnktbW9udGdvbWVyedIBAA?oc=5" >New Hampshire girl, 7, reported missing 2 years after she was last seen</a>  Fox News</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9ZXFJQkZlUVI1bkHSAQA?oc=5" >Manchester Police Offering Cash Reward In Search For 7-Year-Old Harmony Montgomery</a>  CBS Boston</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiXGh0dHBzOi8vd3d3LndtdXIuY29tL2FydGljbGUvbWlzc2luZy1naXJsLW1hbmNoZXN0ZXItaGFybW9ueS1tb250Z29tZXJ5LXJld2FyZC10aXBzLzM4NjU4Mjc10gEA?oc=5" >Tip line, rewards announced for information about missing 7-year-old girl</a>  WMUR Manchester</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9ZTBubDNBTHFjY1XSAQA?oc=5" >#HeyJB on WFLA Now: Missing 7-year-old girl hasn't been seen in 2 years</a>  WFLA News Channel 8</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 3:43 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMicWh0dHBzOi8vd3d3LmJsb29tYmVyZy5jb20vbmV3cy9hcnRpY2xlcy8yMDIyLTAxLTAzL29taWNyb24tcy1taWxkLWluZmVjdGlvbnMtc2lnbmFsLWEtbmV3LXBoYXNlLW9mLWxvd2VyLXNldmVyaXR50gEA?oc=5">Omicron Cases Are Hitting Highs, But New Data Puts End in Sight - Bloomberg</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMicWh0dHBzOi8vd3d3LmJsb29tYmVyZy5jb20vbmV3cy9hcnRpY2xlcy8yMDIyLTAxLTAzL29taWNyb24tcy1taWxkLWluZmVjdGlvbnMtc2lnbmFsLWEtbmV3LXBoYXNlLW9mLWxvd2VyLXNldmVyaXR50gEA?oc=5" >Omicron Cases Are Hitting Highs, But New Data Puts End in Sight</a>  Bloomberg</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiS2h0dHBzOi8vbmV3cy55YWhvby5jb20vcGFuZGVtaWMtZW5kLW9taWNyb24tY2xvdWRzLWZvcmVjYXN0cy0wNjAwMDI3NDcuaHRtbNIBU2h0dHBzOi8vbmV3cy55YWhvby5jb20vYW1waHRtbC9wYW5kZW1pYy1lbmQtb21pY3Jvbi1jbG91ZHMtZm9yZWNhc3RzLTA2MDAwMjc0Ny5odG1s?oc=5" >How will pandemic end? Omicron clouds forecasts for endgame</a>  Yahoo News</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiUGh0dHBzOi8vd3d3Lndhc2hpbmd0b25wb3N0LmNvbS9vcGluaW9ucy8yMDIyLzAxLzAzL29taWNyb24tbG9ja2Rvd25zLWNvdmlkLTIwMjIv0gEA?oc=5" >Opinion | Omicron is bad. But we don't need to resort to lockdowns.</a>  The Washington Post</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiZGh0dHBzOi8vd3d3LmNsaWNrb25kZXRyb2l0LmNvbS9oZWFsdGgvMjAyMi8wMS8wNC9oYXMtdGhlLW9taWNyb24tdmFyaWFudC1jaGFuZ2VkLXRoZS1jb3ZpZC1wYW5kZW1pYy_SAQA?oc=5" >Has the omicron variant changed the COVID pandemic?</a>  WDIV ClickOnDetroit</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9WDBnNUFZY2EyU1XSAQA?oc=5" >Expert says NZ's dodged Omicron 'for now'</a>  1News</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 3:37 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMibGh0dHBzOi8vYXJzdGVjaG5pY2EuY29tL2dhZGdldHMvMjAyMi8wMS9zYW1zdW5ncy0yMDIyLXR2cy1nZXQtMTQ0LWh6LXN1cHBvcnQtYW5kLWEtYnVpbHQtaW4tbmZ0LW1hcmtldHBsYWNlL9IBcmh0dHBzOi8vYXJzdGVjaG5pY2EuY29tL2dhZGdldHMvMjAyMi8wMS9zYW1zdW5ncy0yMDIyLXR2cy1nZXQtMTQ0LWh6LXN1cHBvcnQtYW5kLWEtYnVpbHQtaW4tbmZ0LW1hcmtldHBsYWNlLz9hbXA9MQ?oc=5">Samsung's 2022 TVs get 144 Hz support and a built-in NFT marketplace - Ars Technica</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMibGh0dHBzOi8vYXJzdGVjaG5pY2EuY29tL2dhZGdldHMvMjAyMi8wMS9zYW1zdW5ncy0yMDIyLXR2cy1nZXQtMTQ0LWh6LXN1cHBvcnQtYW5kLWEtYnVpbHQtaW4tbmZ0LW1hcmtldHBsYWNlL9IBcmh0dHBzOi8vYXJzdGVjaG5pY2EuY29tL2dhZGdldHMvMjAyMi8wMS9zYW1zdW5ncy0yMDIyLXR2cy1nZXQtMTQ0LWh6LXN1cHBvcnQtYW5kLWEtYnVpbHQtaW4tbmZ0LW1hcmtldHBsYWNlLz9hbXA9MQ?oc=5" >Samsung's 2022 TVs get 144 Hz support and a built-in NFT marketplace</a>  Ars Technica</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiXWh0dHBzOi8vd3d3LnRoZXZlcmdlLmNvbS8yMDIyLzEvMi8yMjg2MzQ4OS9zYW1zdW5nLTIwMjItbmVvLXFsZWQtOGstNGstdHZzLWFubm91bmNlZC1mZWF0dXJlc9IBAA?oc=5" >Samsung's 2022 TV lineup has big software changes, smaller hardware upgrades</a>  The Verge</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiS2h0dHBzOi8vd3d3LmVuZ2FkZ2V0LmNvbS9zYW1zdW5nLTIwMjItcWxlZC1taWNyb2xlZC04ay00ay10di0wMjAwNDY1OTYuaHRtbNIBAA?oc=5" >Samsung's 2022 QLED TVs include the first 144Hz 4K and 8K sets</a>  Engadget</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9dzlpUmR2bklDYjTSAQA?oc=5" >Samsung announces Odyssey Neo G8, world's first 4K 240Hz monitor</a>  ANI News</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiXGh0dHBzOi8vd3d3LnRoZXZlcmdlLmNvbS8yMDIyLzEvMi8yMjg1ODU3Ny9zYW1zdW5nLWZyYW1lLTIwMjItdHYtbWF0dGUtYW50aXJlZmxlY3RpdmUtc2NyZWVu0gEA?oc=5" >Samsung's latest Frame TVs have a matte screen that looks and feels more like real art</a>  The Verge</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 3:34 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiRGh0dHA6Ly93d3cuZW5nYWRnZXQuY29tL2FybG8tc2VjdXJpdHktc3lzdGVtLWNlcy0yMDIyLTIwMTI1NjE4MC5odG1s0gEA?oc=5">Arlo's Security System has a keypad you can activate with a tap of your phone - Engadget</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiRGh0dHA6Ly93d3cuZW5nYWRnZXQuY29tL2FybG8tc2VjdXJpdHktc3lzdGVtLWNlcy0yMDIyLTIwMTI1NjE4MC5odG1s0gEA?oc=5" >Arlo's Security System has a keypad you can activate with a tap of your phone</a>  Engadget</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiZWh0dHBzOi8vd3d3LnRoZXZlcmdlLmNvbS8yMDIyLzEvMy8yMjg2NTA0MC9hcmxvLXNtYXJ0LWhvbWUtc2VjdXJpdHktc3lzdGVtLXByaWNlLWF2YWlsYWJpbGl0eS1jZXMyMDIy0gEA?oc=5" >Arlo's new DIY smart home security system features NFC technology</a>  The Verge</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMibGh0dHBzOi8vd3d3LmNuZXQuY29tL2hvbWUvc2VjdXJpdHkvYXJsb3MtbmV3LWRpeS1ob21lLXNlY3VyaXR5LXN5c3RlbS13aWxsLWNvbXBldGUtd2l0aC1yaW5nLWFuZC1zaW1wbGlzYWZlL9IBAA?oc=5" >Arlo's new DIY home security system will compete with Ring and SimpliSafe</a>  CNET</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiRGh0dHBzOi8vd3d3LmhlbHBuZXRzZWN1cml0eS5jb20vMjAyMi8wMS8wNC9hcmxvLXRlY2hub2xvZ2llcy1tYXR0ZXIv0gEA?oc=5" >Arlo Technologies partners with Matter to provide home security solutions for customers</a>  Help Net Security</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 3:13 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiWWh0dHBzOi8vd3d3Lm55dGltZXMuY29tLzIwMjIvMDEvMDMvd29ybGQvYWZyaWNhL3NvdXRoLWFmcmljYS1wYXJsaWFtZW50LWZpcmUtc3VzcGVjdC5odG1s0gEA?oc=5">South Africa Parliament: Suspect Charged in Fire to Appear in Court - The New York Times</a></font></h3>
      <p><font size="4"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiWWh0dHBzOi8vd3d3Lm55dGltZXMuY29tLzIwMjIvMDEvMDMvd29ybGQvYWZyaWNhL3NvdXRoLWFmcmljYS1wYXJsaWFtZW50LWZpcmUtc3VzcGVjdC5odG1s0gEA?oc=5" >South Africa Parliament: Suspect Charged in Fire to Appear in Court</a>  The New York Times<b><a href="article.php?loc=US&a=https://news.google.com/stories/CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2l0d1lUS0JCRU5XQko4bjdFZHJpZ0FQAQ?oc=5" ></a></b></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 3:00 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiS2h0dHBzOi8vcGh5cy5vcmcvbmV3cy8yMDIyLTAxLW5hc2Etc3BhY2UtdGVsZXNjb3BlLWh1bmt5LWRvcnktcHJvYmxlbXMuaHRtbNIBAA?oc=5">NASA's new space telescope 'hunky-dory' after problems fixed - Phys.org</a></font></h3>
      <p><font size="4"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiS2h0dHBzOi8vcGh5cy5vcmcvbmV3cy8yMDIyLTAxLW5hc2Etc3BhY2UtdGVsZXNjb3BlLWh1bmt5LWRvcnktcHJvYmxlbXMuaHRtbNIBAA?oc=5" >NASA's new space telescope 'hunky-dory' after problems fixed</a>  Phys.org<b><a href="article.php?loc=US&a=https://news.google.com/stories/CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lyM3VTLUJCRVBQX0I2MkE0UUxTZ0FQAQ?oc=5" ></a></b></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 2:53 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMid2h0dHBzOi8vdGhlaGlsbC5jb20vY2hhbmdpbmctYW1lcmljYS93ZWxsLWJlaW5nL3ByZXZlbnRpb24tY3VyZXMvNTg4MDE1LWFzLW9taWNyb24tc3VyZ2VzLWhlcmVzLXdoYXQtdGhlLWxhdGVzdC1zY2llbmNl0gF7aHR0cHM6Ly90aGVoaWxsLmNvbS9jaGFuZ2luZy1hbWVyaWNhL3dlbGwtYmVpbmcvcHJldmVudGlvbi1jdXJlcy81ODgwMTUtYXMtb21pY3Jvbi1zdXJnZXMtaGVyZXMtd2hhdC10aGUtbGF0ZXN0LXNjaWVuY2U_YW1w?oc=5">As omicron surges here's what the latest science says about the variant | TheHill - The Hill</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMid2h0dHBzOi8vdGhlaGlsbC5jb20vY2hhbmdpbmctYW1lcmljYS93ZWxsLWJlaW5nL3ByZXZlbnRpb24tY3VyZXMvNTg4MDE1LWFzLW9taWNyb24tc3VyZ2VzLWhlcmVzLXdoYXQtdGhlLWxhdGVzdC1zY2llbmNl0gF7aHR0cHM6Ly90aGVoaWxsLmNvbS9jaGFuZ2luZy1hbWVyaWNhL3dlbGwtYmVpbmcvcHJldmVudGlvbi1jdXJlcy81ODgwMTUtYXMtb21pY3Jvbi1zdXJnZXMtaGVyZXMtd2hhdC10aGUtbGF0ZXN0LXNjaWVuY2U_YW1w?oc=5" >As omicron surges here's what the latest science says about the variant | TheHill</a>  The Hill</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiQmh0dHBzOi8vZm9ydHVuZS5jb20vMjAyMi8wMS8wMy9vbWljcm9uLWluZmVjdGlvbnMtc3RyYW5nZS1zeW1wdG9tL9IBAA?oc=5" >Omicron infections are showing a 'very strange symptom'</a>  Fortune</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMia2h0dHBzOi8vd3d3Lm5iY2NoaWNhZ28uY29tL25ld3MvY29yb25hdmlydXMvd2hlbi1jb3VsZC1vbWljcm9uLXN5bXB0b21zLXN0YXJ0LWFmdGVyLWNvdmlkLWV4cG9zdXJlLzI3MTk5NDUv0gFvaHR0cHM6Ly93d3cubmJjY2hpY2Fnby5jb20vbmV3cy9jb3JvbmF2aXJ1cy93aGVuLWNvdWxkLW9taWNyb24tc3ltcHRvbXMtc3RhcnQtYWZ0ZXItY292aWQtZXhwb3N1cmUvMjcxOTk0NS8_YW1w?oc=5" >When Could Omicron Symptoms Start After COVID Exposure?</a>  NBC Chicago</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMibWh0dHBzOi8vd3d3LnRoZW5hdGlvbmFsbmV3cy5jb20vY29yb25hdmlydXMvMjAyMi8wMS8wMy9jb3ZpZC0xOS13aGF0LWFyZS10aGUtc3ltcHRvbXMtb2YtdGhlLW9taWNyb24tdmFyaWFudC_SAQA?oc=5" >Covid-19: what are the symptoms of the Omicron variant</a>  The National</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiS2h0dHBzOi8vd3d3Lm1hcmNhLmNvbS9lbi9saWZlc3R5bGUvMjAyMi8wMS8wMi82MWQxZmQ3ZTI2OGUzZWFlNzE4YjQ1N2QuaHRtbNIBAA?oc=5" >Omicron: The symptoms of the latest strain of the coronavirus</a>  Marca English</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 2:01 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMidWh0dHBzOi8vd3d3Lm5wci5vcmcvc2VjdGlvbnMvY29yb25hdmlydXMtbGl2ZS11cGRhdGVzLzIwMjIvMDEvMDMvMTA2OTk0MjMwNS9zaGVlcC1nb2F0cy1lbmNvdXJhZ2UtdmFjY2luYXRpb24tZ2VybWFuedIBAA?oc=5">Va-a-ax: Sheep and goats form a giant syringe to encourage people to get the jab : Coronavirus Updates - NPR</a></font></h3>
      <p><font size="4"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMidWh0dHBzOi8vd3d3Lm5wci5vcmcvc2VjdGlvbnMvY29yb25hdmlydXMtbGl2ZS11cGRhdGVzLzIwMjIvMDEvMDMvMTA2OTk0MjMwNS9zaGVlcC1nb2F0cy1lbmNvdXJhZ2UtdmFjY2luYXRpb24tZ2VybWFuedIBAA?oc=5" >Va-a-ax: Sheep and goats form a giant syringe to encourage people to get the jab : Coronavirus Updates</a>  NPR<b><a href="article.php?loc=US&a=https://news.google.com/stories/CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lQa3NqUEJCR3NMZkNUVXpjVTB5Z0FQAQ?oc=5" ></a></b></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 1:40 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiYGh0dHBzOi8vcGFnZXNpeC5jb20vMjAyMi8wMS8wMy9hbmR5LWNvaGVuLXN1cHBvcnRzLXZpY2tpLWd1bnZhbHNvbi1hZnRlci1zdGV2ZS1sb2RnZS1lbmdhZ2VtZW50L9IBAA?oc=5">Andy Cohen supports Vicki Gunvalson after Steve Lodge gets engaged - Page Six</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiYGh0dHBzOi8vcGFnZXNpeC5jb20vMjAyMi8wMS8wMy9hbmR5LWNvaGVuLXN1cHBvcnRzLXZpY2tpLWd1bnZhbHNvbi1hZnRlci1zdGV2ZS1sb2RnZS1lbmdhZ2VtZW50L9IBAA?oc=5" >Andy Cohen supports Vicki Gunvalson after Steve Lodge gets engaged</a>  Page Six</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9ZkhQOHNnNktrYXPSAQA?oc=5" >Vicki Gunvalson's Ex Fiancé Steve Lodge Engaged to Orange County Educator | PEOPLE</a>  People</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiUmh0dHBzOi8vd3d3LnlhaG9vLmNvbS9lbnRlcnRhaW5tZW50L3ZpY2tpLWd1bnZhbHNvbnMtZXgtZmlhbmMtc3RldmUtMTE0NzQ2ODc5Lmh0bWzSAVpodHRwczovL3d3dy55YWhvby5jb20vYW1waHRtbC9lbnRlcnRhaW5tZW50L3ZpY2tpLWd1bnZhbHNvbnMtZXgtZmlhbmMtc3RldmUtMTE0NzQ2ODc5Lmh0bWw?oc=5" >Vicki Gunvalson's Ex Fiancé Steve Lodge Engaged to Orange County Educator</a>  Yahoo Entertainment</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9WWJ0MnBNX2ZoVWPSAQA?oc=5" >Steve Lodge Is Engaged to Janis Carlson 3 Months After Split From Ex-Fiancee Vicki Gunvalson</a>  Us Weekly</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMicWh0dHBzOi8vcGVvcGxlLmNvbS90di92aWNraS1ndW52YWxzb24tZ2V0cy1zdXBwb3J0LWZyb20tdGFtcmEtanVkZ2UtYW5keS1jb2hlbi1hZnRlci1leC1zdGV2ZS1sb2RnZS1nZXRzLWVuZ2FnZWQv0gEA?oc=5" >Vicki Gunvalson Gets Support from Tamra Judge and Andy Cohen After Her Ex Steve Lodge Gets Engaged</a>  PEOPLE</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 1:40 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiV2h0dHBzOi8vbnlwb3N0LmNvbS8yMDIyLzAxLzAzL2lzcmFlbC1yZXBvcnRzLXJhcmUtZG91YmxlLWluZmVjdGlvbi1vZi1jb3ZpZC0xOS1hbmQtZmx1L9IBAA?oc=5">Israel reports first case of rare double infection of COVID, flu called 'flurona' - New York Post</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiV2h0dHBzOi8vbnlwb3N0LmNvbS8yMDIyLzAxLzAzL2lzcmFlbC1yZXBvcnRzLXJhcmUtZG91YmxlLWluZmVjdGlvbi1vZi1jb3ZpZC0xOS1hbmQtZmx1L9IBAA?oc=5" >Israel reports first case of rare double infection of COVID, flu called 'flurona'</a>  New York Post </li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiQmh0dHBzOi8vd3d3LnRoZWRhaWx5YmVhc3QuY29tLzIwMjJzLWhvdHRlc3QtbmV3LWlsbG5lc3MtaXMtZmx1cm9uYdIBAA?oc=5" >2022's Hottest New Illness Is Flurona</a>  Daily Beast</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiWGh0dHBzOi8vd3d3LnRoZWN1dC5jb20vMjAyMi8wMS9maXJzdC12ZXJpZmllZC1mbHVyb25hLWluZmVjdGlvbi1jb25maXJtZWQtaW4taXNyYWVsLmh0bWzSAVxodHRwczovL3d3dy50aGVjdXQuY29tL2FtcC8yMDIyLzAxL2ZpcnN0LXZlcmlmaWVkLWZsdXJvbmEtaW5mZWN0aW9uLWNvbmZpcm1lZC1pbi1pc3JhZWwuaHRtbA?oc=5" >What Fresh Hell Is 'Flurona'?</a>  The Cut</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiPGh0dHBzOi8vd3d3LnByZXZlbnRpb24uY29tL2hlYWx0aC9hMzg2NTY4Mzkvd2hhdC1pcy1mbHVyb25hL9IBAA?oc=5" >What Is Flurona? Israel Reports World's First Double Infection From COVID-19 and Flu</a>  Prevention.com</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiigFodHRwczovL3d3dy5maXJzdHBvc3QuY29tL2hlYWx0aC9pc3JhZWwtcmVwb3J0cy1maXJzdC1jYXNlLW9mLWZsb3JvbmEtaGVyZXMtYS1sYXltYW5zLWd1aWRlLXRvLXVuZGVyc3RhbmRpbmctdGhlLW5ldy1kaXNlYXNlLTEwMjUzODQxLmh0bWzSAQA?oc=5" >Israel reports first case of florona: Heres a laymans guide to understanding the new disease</a>  Firstpost</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 12:43 pm</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiZWh0dHBzOi8vd3d3LmtjY2kuY29tL2FydGljbGUvaW93YS1kZXBhcnRtZW50LW9mLXB1YmxpYy1oZWFsdGgtY292aWQtMTktdXBkYXRlLWphbnVhcnktMy0yMDIyLzM4NjU3MDk10gEA?oc=5">Positive COVID-19 tests spike in Iowa while hospitalizations drop slightly - KCCI Des Moines</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiZWh0dHBzOi8vd3d3LmtjY2kuY29tL2FydGljbGUvaW93YS1kZXBhcnRtZW50LW9mLXB1YmxpYy1oZWFsdGgtY292aWQtMTktdXBkYXRlLWphbnVhcnktMy0yMDIyLzM4NjU3MDk10gEA?oc=5" >Positive COVID-19 tests spike in Iowa while hospitalizations drop slightly</a>  KCCI Des Moines</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMidWh0dHBzOi8vd3d3Lm5iY25ld3MuY29tL2hlYWx0aC9oZWFsdGgtbmV3cy9jb3ZpZC13YXJuaW5nLXN5bXB0b21zLWNoaWxkcmVuLWtpZHMtaG9zcGl0YWxpemVkLXJlY29yZC1udW1iZXJzLXJjbmExMDc0MdIBAA?oc=5" >Covid warning symptoms in children: Kids hospitalized in record numbers</a>  NBC News</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiT2h0dHBzOi8vbmV3cy55YWhvby5jb20vY292aWQtY2FzZXMtaG9zcGl0YWxpemF0aW9ucy1yaXNpbmctYW1vbmctMTAwMDM4NDY1Lmh0bWzSAVdodHRwczovL25ld3MueWFob28uY29tL2FtcGh0bWwvY292aWQtY2FzZXMtaG9zcGl0YWxpemF0aW9ucy1yaXNpbmctYW1vbmctMTAwMDM4NDY1Lmh0bWw?oc=5" >FDA OKs Pfizer booster for 12- to 15-year-olds; wait time for 3rd shots now 5 months: COVID updates</a>  Yahoo News</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9NTNfQlp5Um5BWlXSAQA?oc=5" >Kids and COVID-19</a>  Good Morning America</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMikQFodHRwczovL3d3dy5kZXNtb2luZXNyZWdpc3Rlci5jb20vc3RvcnkvbmV3cy9oZWFsdGgvMjAyMi8wMS8wMy9pb3dhLXBvc3QtaG9saWRheS1jb3ZpZC1zdXJnZS0xNzc3My1uZXctY2FzZXMtcmVwb3J0ZWQtb21pY3Jvbi12YXJpYW50LzkwODA1NzEwMDIv0gEA?oc=5" >Iowa COVID positive tests spike 37% after the holidays as omicron spreads through US</a>  Des Moines Register</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 11:54 am</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiW2h0dHBzOi8vd3d3LmNubi5jb20vMjAyMi8wMS8wMy93b3JsZC9mdWxsLW1vb25zLW1ldGVvci1zaG93ZXJzLWVjbGlwc2VzLTIwMjItc2NuL2luZGV4Lmh0bWzSAQA?oc=5">Meteor showers, eclipses, full moons: All of the reasons to look up in 2022 - CNN</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiW2h0dHBzOi8vd3d3LmNubi5jb20vMjAyMi8wMS8wMy93b3JsZC9mdWxsLW1vb25zLW1ldGVvci1zaG93ZXJzLWVjbGlwc2VzLTIwMjItc2NuL2luZGV4Lmh0bWzSAQA?oc=5" >Meteor showers, eclipses, full moons: All of the reasons to look up in 2022</a>  CNN</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiYGh0dHBzOi8vd3d3LnVzYXRvZGF5LmNvbS9zdG9yeS9uZXdzL25hdGlvbi8yMDIyLzAxLzAyL3F1YWRyYW50aWRzLW1ldGVvci1zaG93ZXItMjAyMi85MDcyMDgzMDAyL9IBAA?oc=5" >How to spot the upcoming meteor shower, one of the biggest expected for the year</a>  USA TODAY</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMibWh0dHBzOi8vcGF0Y2guY29tL2NhbGlmb3JuaWEvb2NlYW5zaWRlLWNhbXBwZW5kbGV0b24vb2NlYW5zaWRlcy0yMDIyLWd1aWRlLWVjbGlwc2VzLW1ldGVvci1zaG93ZXJzLXN1cGVybW9vbnPSAYEBaHR0cHM6Ly9wYXRjaC5jb20vY2FsaWZvcm5pYS9vY2VhbnNpZGUtY2FtcHBlbmRsZXRvbi9hbXAvMzAyODYyMzIvb2NlYW5zaWRlcy0yMDIyLWd1aWRlLXRvLWVjbGlwc2VzLW1ldGVvci1zaG93ZXJzLWFuZC1zdXBlcm1vb25z?oc=5" >Oceansides 2022 Guide To Eclipses, Meteor Showers And Supermoons</a>  Patch.com</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiTWh0dHBzOi8vd3d3Lm5ld3NuYXRpb25ub3cuY29tL3NwYWNlL2hvdy10by12aWV3LXRoZS1xdWFkcmFudGlkLW1ldGVvci1zaG93ZXIv0gFRaHR0cHM6Ly93d3cubmV3c25hdGlvbm5vdy5jb20vc3BhY2UvaG93LXRvLXZpZXctdGhlLXF1YWRyYW50aWQtbWV0ZW9yLXNob3dlci9hbXAv?oc=5" >How to view the Quadrantid meteor shower</a>  NewsNation Now</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiWmh0dHBzOi8vd3d3LndhbmUuY29tL3dlYXRoZXIvMjAyMnMtZmlyc3QtbWV0ZW9yLXNob3dlci1mb3JlY2FzdC1jYWxscy1mb3ItYS1uaWNlLXNreS1zaG93L9IBXmh0dHBzOi8vd3d3LndhbmUuY29tL3dlYXRoZXIvMjAyMnMtZmlyc3QtbWV0ZW9yLXNob3dlci1mb3JlY2FzdC1jYWxscy1mb3ItYS1uaWNlLXNreS1zaG93L2FtcC8?oc=5" >2022's first meteor shower forecast calls for a nice sky show</a>  WANE</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 10:01 am</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiU2h0dHBzOi8vd3d3Lm15c21hcnRwcmljZS5jb20vZ2Vhci9vbmVwbHVzLTEwLWRpbWVuc2l0eS05MDAwLXRlc3RpbmctZ2xvYmFsLW1hcmtldHMv0gEA?oc=5">[Exclusive] Possible OnePlus 10 With Dimensity 9000 in the Works, May Enter Testing Soon in Global Markets - MySmartPrice</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiU2h0dHBzOi8vd3d3Lm15c21hcnRwcmljZS5jb20vZ2Vhci9vbmVwbHVzLTEwLWRpbWVuc2l0eS05MDAwLXRlc3RpbmctZ2xvYmFsLW1hcmtldHMv0gEA?oc=5" >[Exclusive] Possible OnePlus 10 With Dimensity 9000 in the Works, May Enter Testing Soon in Global Markets</a>  MySmartPrice</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiOWh0dHBzOi8vZ2l6bW9kby5jb20vdGhlLW9uZXBsdXMtMTAtcHJvLWlzLWhlcmUtMTg0ODI5NTY5MtIBAA?oc=5" >OnePlus Just Teased the OnePlus 10 Pro, and It Has a Very Samsung Look</a>  Gizmodo</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiV2h0dHBzOi8vd3d3LnRoZXZlcmdlLmNvbS8yMDIyLzEvMy8yMjg0OTg2OC9vbmVwbHVzLXByby1jaGluYS1sYXVuY2gtamFudWFyeS0xMXRoLWRlc2lnbtIBAA?oc=5" >OnePlus 10 Pro official teaser shows off triple rear cameras and Hasselblad branding</a>  The Verge</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiQmh0dHBzOi8vd3d3LmRyb2lkLWxpZmUuY29tLzIwMjIvMDEvMDMvb25lcGx1cy0xMC1wcm8tcmVsZWFzZS1kYXRlL9IBAA?oc=5" >OnePlus 10 Pro is Official and We Know When It's Coming</a>  Droid Life</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiX2h0dHBzOi8vd3d3LmFuZHJvaWRwb2xpY2UuY29tL2EtdmFyaWFudC1vZi10aGUtb25lcGx1cy0xMC1taWdodC1zaGlwLXdpdGgtYS1tZWRpYXRlay1wcm9jZXNzb3Iv0gEA?oc=5" >A variant of the OnePlus 10 might ship with a MediaTek processor</a>  Android Police</li></li></ol></font></p></p>
      <p><small>Posted on 3 January 2022 | 5:59 am</small></p>
 
   
      <h3><font size="5"><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMihgFodHRwczovL3RlY2guaGluZHVzdGFudGltZXMuY29tL3RlY2gvbmV3cy9uYXNhLXJhaXNlcy13YXJuaW5nLW9mLTUtYXN0ZXJvaWRzLWhlYWRpbmctdG93YXJkcy1lYXJ0aC1pbi1qYW51YXJ5LTIwMjItNzE2NDExMzYzODMyNDEuaHRtbNIBAA?oc=5">NASA raises warning of 5 asteroids heading towards Earth in January, 2022 - HT Tech</a></font></h3>
      <p><font size="4"><ol><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMihgFodHRwczovL3RlY2guaGluZHVzdGFudGltZXMuY29tL3RlY2gvbmV3cy9uYXNhLXJhaXNlcy13YXJuaW5nLW9mLTUtYXN0ZXJvaWRzLWhlYWRpbmctdG93YXJkcy1lYXJ0aC1pbi1qYW51YXJ5LTIwMjItNzE2NDExMzYzODMyNDEuaHRtbNIBAA?oc=5" >NASA raises warning of 5 asteroids heading towards Earth in January, 2022</a>  HT Tech</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiR2h0dHBzOi8vd3d3LnRoZS1zdW4uY29tL25ld3MvNDM4Njc0NS9uYXNhLWZpdmUtYXN0ZXJvaWRzLWVhcnRoLWphbnVhcnkv0gEA?oc=5" >NASA warns at least FIVE asteroids are heading toward Earth in January and one is the size of Big Ben...</a>  The US Sun</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiLGh0dHBzOi8vd3d3Lmpwb3N0LmNvbS9zY2llbmNlL2FydGljbGUtNjkwMzgw0gEA?oc=5" >Don't look up! Apocalypse-level asteroid to fly past Earth this month</a>   The Jerusalem Post</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMikQFodHRwczovL3RlY2guaGluZHVzdGFudGltZXMuY29tL3RlY2gvbmV3cy9uYXNhLWFzdGVyb2lkLTItNS10aW1lcy10aGUtaGVpZ2h0LW9mLWVtcGlyZS1zdGF0ZS1idWlsZGluZy10by1wYXNzLWVhcnRoLW9uLWphbi0xOC03MTY0MTIwNTA4MjI1NC5odG1s0gEA?oc=5" >NASA: Asteroid 2.5 times the height of Empire State Building to pass Earth on Jan 18</a>  HT Tech</li><li><a href="article.php?loc=US&a=https://news.google.com/__i/rss/rd/articles/CBMiY2h0dHBzOi8vd3d3LmRhaWx5c3Rhci5jby51ay9uZXdzL2xhdGVzdC1uZXdzL2tpbG9tZXRyZS13aWRlLXBvdGVudGlhbGx5LWhhemFyZG91cy1hc3Rlcm9pZC0yNTg0MTg1NNIBAA?oc=5" >Kilometre-wide 'potentially hazardous' asteroid will shoot past Earth this month</a>  Daily Star</li></li></ol></font></p></p>
      <p><small>Posted on 2 January 2022 | 10:13 am</small></p>
 
    <p><center><small>v1.0 Powered by Mozilla Readability (Andres Rey PHP Port) and SimplePie</small><center></p>
</body>
</html>
`;

export const getTestRender = async () => {
  const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath,
    headless: false,
    ignoreHTTPSErrors: true,
  });

  const page = await browser.newPage();

  await page.setContent(testHtml);

  const pdf = await page.pdf({
    format: "a4",
  });

  await browser.close();
  return pdf;
};
